services:
  thoracic-app:
    build: .
    container_name: thoracic-app
    ports:
      - "0.0.0.0:8501:8501"
    volumes:
      - ./results:/app/results
      # If you have a local secrets.toml, uncomment the next line to mount it
      # - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml
    restart: always
